trace:
  endpoint: http://100.64.1.1:30807/api/traces
server:
  http:
    addr: 0.0.0.0:8030
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9030
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(100.64.1.1:30882)/linkme_microservices?parseTime=True&loc=Local
  redis:
    addr: 100.64.1.1:30884
    read_timeout: 0.2s
    write_timeout: 0.2s
service:
  etcd:
    addr:
      - 127.0.0.1:2379
    timeout: 5s
