trace:
  endpoint: http://100.64.1.1:30807/api/traces
server:
  http:
    addr: "0.0.0.0:8020"
    timeout: 1s
  grpc:
    addr: "0.0.0.0:9020"
    timeout: 1s
data:
  database:
    source: root:root@tcp(100.64.1.1:30882)/linkme_microservices?parseTime=True&loc=Local
  redis:
    addr: "100.64.1.1:30884"
  mongo:
    addr: "mongodb://root:root@100.64.1.1:30883"
  kafka:
    addr:
      - "100.64.1.1:30880"
service:
  etcd:
    addr:
      - "127.0.0.1:2379"
    timeout: 5s